# Generated by Django 5.0 on 2024-08-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_erp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableOl',
        ),
    ]
