# Generated by Django 5.0 on 2024-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_erp', '0002_delete_tableol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='Name', verbose_name='Имя пользователя')),
                ('email', models.TextField(db_column='Email', unique=True, verbose_name='Почтовый ящик')),
                ('age', models.IntegerField(db_column='Age', verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Таблица ol',
                'verbose_name_plural': 'Таблица ol',
                'db_table': 'ol',
                'ordering': ['name'],
            },
        ),
    ]
